name: Update LLM Perf Leaderboard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update_llm_perf_leaderboard:
    if: ${{
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      contains( github.event.pull_request.labels.*.name, 'leaderboard') ||
      contains( github.event.pull_request.labels.*.name, 'update_leaderboard')
      }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install pandas huggingface_hub[hf_transfer]
          pip install git+https://github.com/huggingface/optimum-benchmark.git
          pip install -e .


      - name: Update Open LLM Data
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_HUB_ENABLE_HF_TRANSFER: 1
        run: |
          pip install -e .
          llm-perf update-leaderboard
